Update photo-sphere-viewer.js to v4
nextcloud/files_photospheres pull request #76
Opened 2021-05-31 14:41 UTC by R0Wi

related to #1

2022-05-06 22:47 UTC, bahnwaerter requested changes
Everything looks fine to me except some minor indentation errors. Please fix the incorrect indentations. Note that I only reviewed the code and haven't done any manual testing yet.

2022-05-06 22:47 UTC, bahnwaerter commented on tests/Testdata/pos1.json
> +	"fullWidth": 13934,
Please indent the lines evenly.

```suggestion
  "fullWidth": 13934,
```

2022-05-06 22:47 UTC, bahnwaerter commented on tests/Testdata/pos10.json
> +	"fullWidth": 6032,
Please indent the lines evenly.

```suggestion
  "fullWidth": 6032,
```

2022-05-06 22:47 UTC, bahnwaerter commented on tests/Testdata/pos2.json
> +	"fullWidth": null,
Please indent the lines evenly.

```suggestion
  "fullWidth": null,
```

2022-05-06 22:47 UTC, bahnwaerter commented on tests/Testdata/pos3.json
> +	"fullWidth": 21243,
Please indent the lines evenly.

```suggestion
  "fullWidth": 21243,
```

2022-05-07 07:43 UTC, R0Wi commented on tests/Testdata/pos3.json
> +	"fullWidth": 21243,
A bit unfair since VSCode shows them all aligned :smile: Reformatted ...

2022-05-07 08:01 UTC, R0Wi commented
@bahnwaerter i did a rebase on the NC24 compatible version and forced pushed including the requested changes. I think we have to manually backport this to NC23 stable in a separate PR (see https://github.com/nextcloud/files_photospheres/pull/89)

2022-05-07 08:09 UTC, merged